### ISSUE TITLE
Does ScaledYOLOv4 use Deformable Convolution?

### ISSUE THREAD

**Issue by songyuc** [WongKinYiu/ScaledYOLOv4#103]
Hi guys,
I want to know whether ScaledYOLOv4 uses Deformable Convolution. Although according to the paper, it seems ScaledYOLOv4 doesn't use Deformable Convolution, I just want confirm whether it use any techniques related to Deformable Convolution or not.

Your answer or idea will be appreciated!

**Comment by AlexeyAB** [comment]
No. 
Scaled-YOLOv4 doesn't use Deformable Convolution.

**Comment by songyuc** [comment]
@AlexeyAB , thanks sincerely for your answer!
