### ISSUE TITLE
"python setup.py build install"  is failed!

### ISSUE THREAD

**Issue by TaoHervor** [WongKinYiu/ScaledYOLOv4#106]
creating /home/cyy/yolo/mish-cuda/build/temp.linux-x86_64-3.7/csrc/cuda
Emitting ninja build file /home/cyy/yolo/mish-cuda/build/temp.linux-x86_64-3.7/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
1.10.2
g++ -pthread -shared -B /home/cyy/anaconda3/envs/open-mmlab/compiler_compat -L/home/cyy/anaconda3/envs/open-mmlab/lib -Wl,-rpath=/home/cyy/anaconda3/envs/open-mmlab/lib -Wl,--no-as-needed -Wl,--sysroot=/ /home/cyy/yolo/mish-cuda/build/temp.linux-x86_64-3.7/csrc/cpu/mish_cpu.o /home/cyy/yolo/mish-cuda/build/temp.linux-x86_64-3.7/csrc/cuda/mish_cuda.o /home/cyy/yolo/mish-cuda/build/temp.linux-x86_64-3.7/csrc/cuda/mish_kernel.o -L/home/cyy/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib -L/usr/local/cuda/lib64 -lc10 -ltorch -ltorch_cpu -ltorch_python -lcudart -lc10_cuda -ltorch_cuda -o build/lib.linux-x86_64-3.7/mish_cuda/_C.cpython-37m-x86_64-linux-gnu.so

g++: error: /home/cyy/yolo/mish-cuda/build/temp.linux-x86_64-3.7/csrc/cpu/mish_cpu.o: No such file or directory
g++: error: /home/cyy/yolo/mish-cuda/build/temp.linux-x86_64-3.7/csrc/cuda/mish_cuda.o: No such file or directory
g++: error: /home/cyy/yolo/mish-cuda/build/temp.linux-x86_64-3.7/csrc/cuda/mish_kernel.o: No such file or directory
error: command 'g++' failed with exit status 1

**Comment by TaoHervor** [comment]
I solved id

**Comment by k1anshul** [comment]
How did you solve this @TaoHervor ?

**Comment by xxcheng0708** [comment]
I have the same problem with you .

**Comment by carihkl** [comment]
for mish_kernel.o: No such file or directory, the following link worked for me.
Can run "ninja" at the build.ninja directory to further debug
https://github.com/thomasbrandon/mish-cuda/issues/9#issue-747273937

**Comment by qxqjjbnxy** [comment]
@TaoHervor how did you solve this problem?
