### ISSUE TITLE
What is the annotation type?

### ISSUE THREAD

**Issue by HansolHyewon** [WongKinYiu/ScaledYOLOv4#110]
When creating a label txt file,
I am wondering whether to make it with xyxy or xywh.

**Comment by WongKinYiu** [comment]
`<category_id> <center_x_in_ratio> <center_y_in_ratio> <width_in_ratio> <height_in_ratio>`

**Comment by HansolHyewon** [comment]
> `<category_id> <center_x_in_ratio> <center_y_in_ratio> <width_in_ratio> <height_in_ratio>`

thanks. I solved this problem.
