### ISSUE TITLE
Which weight should use for inference ?

### ISSUE THREAD

**Issue by saikrishnadas** [WongKinYiu/ScaledYOLOv4#111]
i get two types of weight file - weight_strip.pt and weight.pt, which one should i use for my production inference ? 
@WongKinYiu

**Comment by WongKinYiu** [comment]
strip

**Comment by saikrishnadas** [comment]
What the difference between .pt and strip.pt weights ?

**Comment by WongKinYiu** [comment]
.pt includes some training info, strip.pt only contains weights.

**Comment by saikrishnadas** [comment]
But accuracy is the same right ? i mean there wont be any drop in accuracy ?

**Comment by saikrishnadas** [comment]
@WongKinYiu

**Comment by WongKinYiu** [comment]
same
