### ISSUE TITLE
Does ScaledYOLOv4 use any normalization (mean/std) or preprocess operations?

### ISSUE THREAD

**Issue by songyuc** [WongKinYiu/ScaledYOLOv4#113]
Hi, guys,
I want to know whether ScaledYOLOv4 use any normalization (mean/std) for image channels or preprocess operations?

Your answer or idea will be appreciated!

**Comment by WongKinYiu** [comment]
no.

**Comment by songyuc** [comment]
@WongKinYiu ，thanks sincerely for your guide!
