### ISSUE TITLE
Runtime Error broken pipe

### ISSUE THREAD

**Issue by sirhikesalot** [WongKinYiu/ScaledYOLOv4#118]
I am attempting to train custom data on an aws g class ec2 instance containing 4 tesla v11 gpus and I keep running into a Runtime Error: Broken pipe. The cmd I'm running is:
`python3.8 -m torch.distributed.launch --nproc_per_node 4 train.py --batch-size 64 --img 1280 1280 --data objdet.yaml --cfg models/yolov4-p6.yaml --weights yolov4-p6.pt --sync-bn --device 0,1,2,3 --name yolov4-p6 --epochs 300`

And here is the stack trace:
![image](https://user-images.githubusercontent.com/32233555/103698517-4f3b4c00-4f56-11eb-92c1-b21a3ac7295b.png)

**Comment by WongKinYiu** [comment]
it seems you type `Ctrl+C` to interrupt the training.

**Comment by sirhikesalot** [comment]
@WongKinYiu the keyboard interrupt is odd because I'm almost certain that I did not press ctrl-c. I also tried from a fresh conda env and got the same error. However, I did succeed using your docker instructions, so I will mark this as closed. Thanks.
