### ISSUE TITLE
Training Time Boost

### ISSUE THREAD

**Issue by ozgurkan** [WongKinYiu/ScaledYOLOv4#122]
First of all, thank you for presenting such a model. I'm working on sperm detection in videos for my graduation project. I have previously trained a model using YoloV5 and completed the training in 4000 steps. It was incredibly fast. I also started a training with ScaledYolov4. But I saw that he was trained a little slowly I am open to your suggestions on this subject. I took the image sizes as 640x640 and used the batch size as 16. ScaledYolov4 approx 4000 steps and have any suggestions to train faster? Thank you from now.

**Comment by WongKinYiu** [comment]
In my experiment, the training speed of yolov4-csp is almost as same as yolov5.
I guess you are using yolov4-large.
larger model/resolution will spend more training time, the better way to speed up is use multiple gpus for training.

**Comment by ozgurkan** [comment]
@WongKinYiu Thank you for your advice. I will try what you wrote.
