### ISSUE TITLE
yolov4-csp和yolov4-pacsp的区别

### ISSUE THREAD

**Issue by DrewdropLife** [WongKinYiu/ScaledYOLOv4#123]
您好，我注意到您另一个项目PyTorch-YOLOv4中包含了yolov4-pacsp.cfg
而我对比了该项目ScaledYOLOv4下的yolov4-csp.cfg
发现二者仅激活函数不同，因此我想确认一下第一个项目中的yolov4-pacsp.cfg也是scaled论文中的实现吗？

**Comment by WongKinYiu** [comment]
yolov4-csp in scaled yolov4 is as same as yolov4-pacsp-mish in pytorch yolo.
