### ISSUE TITLE
Problems when training custom datasets

### ISSUE THREAD

**Issue by ghost** [WongKinYiu/ScaledYOLOv4#126]
After changing the classes of the 3 yolo block to the number of classes of custom data in the yolov4-csp.cfg file and training, the following error occurs. I am wondering if it is correct to not change this value when training custom data. Thank you.

yolov4-csp.cfg
[yolo]
mask = 0,1,2
anchors = 12, 16, 19, 36, 40, 28, 36, 75, 76, 55, 72, 146, 142, 110, 192, 243, 459, 401
classes=80 <<-- this value

[Error]
p = p.view(bs, self.na, self.no, self.ny, self.nx).permute(0, 1, 3, 4, 2).contiguous()  # prediction
RuntimeError: shape '[8, 3, 10, 80, 80]' is invalid for input of size 13056000

**Comment by LukeAI** [comment]
@bluein I think you need to change classes [nc] in the yaml file as well, also set  filters to: (classes + 5)x3 in the conv layer before each yolo block. https://github.com/AlexeyAB/darknet#how-to-train-to-detect-your-custom-objects

**Comment by ghost** [comment]
@LukeAI Thank you for your quick reply!

**Comment by engrjav** [comment]
@ghost the suggestion for changing filters is for darknet frame work while in this code we are using pytorch.

where did you make changes in pytorch?
