### ISSUE TITLE
How to get the same detailed evaluation results as you

### ISSUE THREAD

**Issue by Jeozhao** [WongKinYiu/ScaledYOLOv4#130]
Hi wongkinyiu,

When I used test.py to evaluate the model, I found that even if I add the verbose tag, the result is only three lines at most. Not as detailed as the example you gave. How can I obtain more detailed evaluation results?

Thank you!

**Comment by WongKinYiu** [comment]
The shown results are from pycocotool, if you want to obtain the same information, you have to make your own ground truth file in coco json format.
Then put your ground truth file name in https://github.com/WongKinYiu/ScaledYOLOv4/blob/yolov4-csp/test.py#L245.

**Comment by Jeozhao** [comment]
Thank you so much!
I have solved my problem!

**Comment by engrjav** [comment]
> The shown results are from pycocotool, if you want to obtain the same information, you have to make your own ground truth file in coco json format. Then put your ground truth file name in https://github.com/WongKinYiu/ScaledYOLOv4/blob/yolov4-csp/test.py#L245.

@WongKinYiu  thanks for your amazing work

can you tell what to ammend in line 245 as line 245 is    print(pf % ('all', seen, nt.sum(), mp, mr, map50, map))
