### ISSUE TITLE
many training images mostly contain grey

### ISSUE THREAD

**Issue by LukeAI** [WongKinYiu/ScaledYOLOv4#139]
Many of the training images, as shown by tensorboard, are mostly grey.
![individualImage](https://user-images.githubusercontent.com/43993778/104845842-71768780-58cf-11eb-9948-596f35abd3b6.png)
`python yolov4-large/train.py --device 0 --batch-size 10 --data yolov4-large/data/apm.yaml --cfg yolov4-large/models/yolov4-p5-apm.yaml --weights 'yolov4-large/weights/yolov4-p5.pt' --img-size 640 --name yolov4-p5 --cache-images --epochs 300`

Is this expected behaviour?

**Comment by cyrilzakka** [comment]
I'm pretty sure that's just the padding color on the data augs.

**Comment by LukeAI** [comment]
yeah, I think it's intentional.
