### ISSUE TITLE
Just a question about repositories...

### ISSUE THREAD

**Issue by dsantiago** [WongKinYiu/ScaledYOLOv4#148]
Will you just keep updating your other repository `PyTorch_YOLOv4`? As it is a bit confusing as here we got CSP Models and there we got the CSP models too and you are more active on the other repo.

**Comment by WongKinYiu** [comment]
You can think that the `PyTorch_YOLOv4` repository is a framework which is similar to mmdetection.
And `ScaledYOLOv4` repository is one of method which is developed with `PyTorch_YOLOv4`.

**Comment by dsantiago** [comment]
Ohh i see, but `ScaledYOLOv4` is kind of a more sophisticated model, right? Thanks for the response and your awesome job with the models!
