### ISSUE TITLE
How does FPS be computed?

### ISSUE THREAD

**Issue by feiyuhuahuo** [WongKinYiu/ScaledYOLOv4#15]
Hi, I'd like to know how FPS is computed? How does the time consumption per detection be considered? Include data input, network forward and NMS or just network forward and NMS or any other way?

**Comment by WongKinYiu** [comment]
FPS value with * include model inference and NMS.
for yolov4-csp and yolov4-tiny, use: 
`./darknet detector demo cfg/coco.data cfg/yolo.cfg weights/yolo.weights test.mp4 -dont_show` 

FPS value without * only include model inference.
 `./darknet detector demo cfg/coco.data cfg/yolo.cfg weights/yolo.weights test.mp4 -dont_show -benchmark`

**Comment by feiyuhuahuo** [comment]
Thanks.

**Comment by mls1999725** [comment]
Hi, I wonder where is the test.mp4?

**Comment by WongKinYiu** [comment]
any .mp4 file can be used.

**Comment by mls1999725** [comment]
Thanks. By the way, is it possible to test fps using MSCOCO and how?

**Comment by WongKinYiu** [comment]
`./darknet detector test cfg/coco.data cfg/yolo.cfg weights/yolo.weights test.jpg -dont_show`

**Comment by mls1999725** [comment]
> FPS value with * include model inference and NMS.
> for yolov4-csp and yolov4-tiny, use:
> `./darknet detector demo cfg/coco.data cfg/yolo.cfg weights/yolo.weights test.mp4 -dont_show`
Thanks. I use this command to test fps of yolov4-csp, and I set size as 640x640, batchsize as 1, but fps is just 52.2. I'd like to know if anything is wrong during testing?

**Comment by mls1999725** [comment]
Hi, I'm very interested in this work and I'd like to know whether tensorRT was used during testing?

**Comment by WongKinYiu** [comment]
tensorRT is not used, please testing with cuda10, the performance on cuda11 is not good.
[my environment](https://github.com/WongKinYiu/ScaledYOLOv4/tree/yolov4-tiny#installation)

**Comment by mls1999725** [comment]
Thanks! I have tested fps on yolov4-csp. I also wonder how I can test fps on yolov4-p5, yolov4-p6 and yolov4-p7?
