### ISSUE TITLE
About the nominal batch size

### ISSUE THREAD

**Issue by jasonchenPJ** [WongKinYiu/ScaledYOLOv4#161]
Hi, 
Could you explain the purpose of "nbs = 64" setting?
If i change the "img-size" of arg. setting, may i need to modify it?
thanks

**Comment by LukeAI** [comment]
it looks like the optimizer only steps when loss has been calculated and accumulated for 64 images. pretty cool and I hadn't spotted this - so we can effectively train very large batch sizes with limited VRAM.

I'd be interested to know if there is any real difference other than training time for the batch size selected?

It'd also be interesting to experiment with nbs - maybe for smaller datasets "32" might be better.
