### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by nvnnghia** [WongKinYiu/ScaledYOLOv4#17]
Thanks for sharing the great work. Would you mind adding a licence?

**Comment by WongKinYiu** [comment]
darknet version follow the licence of [darknet](https://github.com/AlexeyAB/darknet).
pytorch version follow the licence of [PyTorch_YOLOv4](https://github.com/WongKinYiu/PyTorch_YOLOv4).

**Comment by nvnnghia** [comment]
Thanks @WongKinYiu
