### ISSUE TITLE
Pytorch and CUDA versions for training without Docker?

### ISSUE THREAD

**Issue by ramanathan831** [WongKinYiu/ScaledYOLOv4#183]
Hi, there seems to be an error with Pytorch 1.7.1 and CUDA 10.2 : File "/home/ram/miniconda3/envs/scaled-yolo/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 420, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDA error: invalid device function

Is there any requirements for CUDA and Pytorch version for the training to run smoothly?

**Comment by WongKinYiu** [comment]
https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/rel_20-08.html

also i have tried `pip install`:
```
Cython
matplotlib>=3.2.2
numpy>=1.18.5
opencv-python>=4.1.2
Pillow
PyYAML>=5.3.1
scipy>=1.4.1
tensorboard>=1.5
torch==1.7.0
torchvision==0.8.1
tqdm>=4.41.0
```

**Comment by ramanathan831** [comment]
Hi, I did install according to your comment, still, I am facing the same issue.
'''
pip install Cython
pip install matplotlib>=3.2.2
pip install numpy>=1.18.5
pip install opencv-python>=4.1.2
pip install Pillow
pip install PyYAML>=5.3.1
pip install scipy>=1.4.1
pip install tensorboard>=1.5
pip install torch==1.7.0
pip install torchvision==0.8.1
pip install tqdm>=4.41.0
'''

**Comment by ramanathan831** [comment]
After doing a complete cleanup of virtual-env and installing the above versions solved the issue. Thanks.
