### ISSUE TITLE
[TensorRT] ERROR: INVALID_ARGUMENT: getPluginCreator could not find plugin ScatterND version 1

### ISSUE THREAD

**Issue by ShiHangY** [WongKinYiu/ScaledYOLOv4#190]
When I try to convert onnx into tensorrt engine, it fails at onnx parser and return this error.
[TensorRT] ERROR: INVALID_ARGUMENT: getPluginCreator could not find plugin ScatterND version 1

onnx version : 1.6.0
Tensorrt version : 7.1.3.4

**Comment by sakulh** [comment]
Please paste your command for conversion to tensorrt.
