### ISSUE TITLE
Save model weights after every 10 epochs

### ISSUE THREAD

**Issue by jigsawcoder** [WongKinYiu/ScaledYOLOv4#195]
I am training scaled yolov4 p7 on my custom dataset. The weights of the model are being saved after each epoch but I wish it to be saved after every 10(example) epochs. I found the by adding --nosave argument, only the last weights are saved but I want to save weights after 10 epochs.
Please help
Thanks in advance

**Comment by WongKinYiu** [comment]
https://github.com/WongKinYiu/ScaledYOLOv4/blob/yolov4-large/train.py#L346
``` python
if ((epoch +1) % 10) == 0:
```
