### ISSUE TITLE
what is OSAnet ？

### ISSUE THREAD

**Issue by x2ss** [WongKinYiu/ScaledYOLOv4#23]
Hi,

Thanks for your sharing. When reading the paper, I am puzzled about about what is OSAnet is. I can not find the full name of OSAnet. 
Would you please kindly tell me the full name of OSAnet?

Thank you and best regards!

**Comment by WongKinYiu** [comment]
I use OSA module in VoVNet to build OSANet.

**Comment by x2ss** [comment]
> I use OSA module in VoVNet to build OSANet.

Thanks！
