### ISSUE TITLE
multi-scale

### ISSUE THREAD

**Issue by SUNziwei0527** [WongKinYiu/ScaledYOLOv4#233]
在multi-scale训练时，只改变了图片的大小，但是label的大小没有改变，请问label操作在哪一部分

**Comment by WongKinYiu** [comment]
label 是 ratio 不是絕對值, 所以不用改.

**Comment by larsoncs** [comment]
@WongKinYiu ，图片大小改变了，框大小没有改变

**Comment by WongKinYiu** [comment]
框的 label 是用比例
640x480 的 0.5 倍是 320x240
1280x960 的 0.5 倍是 640x480
圖片縮放 label 不用改

**Comment by SUNziwei0527** [comment]
谢谢您，我懂了。
