### ISSUE TITLE
Extra boxes coming in when testing

### ISSUE THREAD

**Issue by makaveli10** [WongKinYiu/ScaledYOLOv4#234]
I have some extra boxes coming in when testing it on sample images. cannot make much sense why its happening.
![_bus](https://user-images.githubusercontent.com/39617050/117116079-86f2bd00-adab-11eb-91d4-39ae220106d6.jpg)
![_zidane](https://user-images.githubusercontent.com/39617050/117116093-89edad80-adab-11eb-8daa-f49375666d8d.jpg)

THe thing I have used the same NMS function which gives correct outputs for yolov4

**Comment by WongKinYiu** [comment]
i guess your code, cfg and weight are download from different place.
the results seems caused by different decoder.
![image](https://user-images.githubusercontent.com/12152972/118217167-7deaa580-b4a7-11eb-982a-6b7021d2ae9c.png)
