### ISSUE TITLE
statistics

### ISSUE THREAD

**Issue by xhumanz** [WongKinYiu/ScaledYOLOv4#238]
-

**Comment by WongKinYiu** [comment]
please use test.py to alculate the accuracy.

**Comment by xhumanz** [comment]
is the conf in line 130 is the accuracy ?

**Comment by xhumanz** [comment]
@WongKinYiu

**Comment by WongKinYiu** [comment]
https://github.com/WongKinYiu/ScaledYOLOv4/blob/yolov4-csp/test.py#L210-L216
