### ISSUE TITLE
What is OSANet mentioned in the paper

### ISSUE THREAD

**Issue by smart0eddie** [WongKinYiu/ScaledYOLOv4#24]
Hi, you mentioned in the paper that you apply OSANet architecture for tiny model, but I cannot find its reference.
Where may I get more detailed information about OSANet?

By the way, should it be depth $\Beta$ and width $\gamma$ in Table 1?

Thanks.

**Comment by zys1994** [comment]
@smart0eddie  you can find it from paper:VoVNet

**Comment by smart0eddie** [comment]
thanks

**Comment by WongKinYiu** [comment]
噢! 多謝! 是的, 表1應修正為深度$\beta$和寬度$\gamma$, 內文是正確的
