### ISSUE TITLE
Why does Scaled YOLOv4 use GIoU  loss and not CIoU loss?

### ISSUE THREAD

**Issue by Jesperpaulsen** [WongKinYiu/ScaledYOLOv4#248]
I might be wrong, but I thought YOLOv4 used CIoU loss at is has proven to have better performance than GIoU. Why does Scaled YOLOv4 use GIoU and not CIoU?

**Comment by WongKinYiu** [comment]
CIoU is used.
https://github.com/WongKinYiu/ScaledYOLOv4/blob/yolov4-csp/utils/loss.py#L99

**Comment by Jesperpaulsen** [comment]
Oh, my bad. Thanks for the answer @WongKinYiu . Really appreciate your quick response. What is the reason for logging GIoU to the tensorboard and not CIoU?

**Comment by WongKinYiu** [comment]
Because the framework does not support the ciou at the beginning. Now it supports many kind of iou loss.
https://github.com/WongKinYiu/ScaledYOLOv4/blob/yolov4-csp/utils/general.py#L211

**Comment by Jesperpaulsen** [comment]
Ah, that makes sense! Thank you so much for your answers and a great model.
