### ISSUE TITLE
Use of CutMix batch augmentation

### ISSUE THREAD

**Issue by droomkan** [WongKinYiu/ScaledYOLOv4#254]
Hello,

I have a question. I was wondering if CutMix is already implemented in the data-augmentation steps. 
I see it is commented out in the .cfg files, but I cant find any functions in the source code that actually implement it. 
If I undo the comment in the .cfg files for training, the results for the first batches don't show any CutMix images in the batch. 

Since the original darknet YoloV4 does use CutMix I thought it to be a bit strange that I can't find any implementation of it in your code. So, this is a little confusing to me. Because I really want to see what kind of impact CutMix has on model performance, along with all the other data-augmentation steps. 

But, perhaps there is a good reason you have not yet implemented it or I am an idiot who can't seem to find it. 

Thank you!

**Comment by droomkan** [comment]
@WongKinYiu

**Comment by WongKinYiu** [comment]
```
            def CutMix(image, boxes, r_image, r_boxes):
                mixup_image = image.copy()
                imsize = min(image.shape[0], r_image.shape[0])
                x1, y1 = [int(random.uniform(imsize * 0.0, imsize * 0.45)) for _ in range(2)]
                x2, y2 = [int(random.uniform(imsize * 0.55, imsize * 1.0)) for _ in range(2)]
                
                mixup_boxes = r_boxes.copy()
                area = (r_boxes[:, 3] - r_boxes[:, 1]) * (r_boxes[:, 4] - r_boxes[:, 2])
                
                mixup_boxes[:, [1, 3]] = mixup_boxes[:, [1, 3]].clip(min=x1, max=x2)
                mixup_boxes[:, [2, 4]] = mixup_boxes[:, [2, 4]].clip(min=y1, max=y2)
                mixup_boxes = mixup_boxes.astype(np.int32)
                #cropped w, h, area
                w = mixup_boxes[:, 3] - mixup_boxes[:, 1]
                h = mixup_boxes[:, 4] - mixup_boxes[:, 2]
                area0 = w * h
                ar = np.maximum(w / (h + 1e-16), h / (w + 1e-16))
                
                mixup_boxes = mixup_boxes[np.where((w > 2) & (h > 2) & (area / (area0 + 1e-16) > 0.2) & (ar < 20))]
                mixup_image[y1:y2, x1:x2] = (mixup_image[y1:y2, x1:x2] + r_image[y1:y2, x1:x2])/2

                mixup_boxes = np.concatenate((boxes, mixup_boxes), axis=0)
                return mixup_image, mixup_boxes
```
implementation in https://github.com/TaoXieSZ/UD-CISC849
