### ISSUE TITLE
Yolo-v4-p5. Got low AP( 0.00114) on test.py

### ISSUE THREAD

**Issue by SashaAlderson** [WongKinYiu/ScaledYOLOv4#274]
pytorch 1.9.0, cuda 11.1, mish-cuda 0.0.3
Input:
:$ python test.py --img 896 --conf 0.001 --batch 8 --device 0 --data coco.yaml --weights weights/yolov4-p5.pt
Output:
C:\Anaconda\lib\site-packages\torch\nn\functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  ..\c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
Scanning labels coco\val2017\labels.cache (4952 found, 0 missing, 48 empty, 0 duplicate, for 5000 images): 100%|##########| 5000/5000 [00:00<00:00, 16891.86it/s]
               Class      Images     Targets           P           R      mAP@.5  mAP@.5:.95: 100%|##########| 625/625 [02:06<00:00,  4.93it/s]
Namespace(augment=False, batch_size=8, conf_thres=0.001, data='.\\data\\coco.yaml', device='0', img_size=896, iou_thres=0.65, merge=False, save_json=True, save_txt=False, single_cls=False, task='val', verbose=False, weights=['weights/yolov4-p5.pt'])
Using CUDA device0 _CudaDeviceProperties(name='NVIDIA GeForce RTX 3070', total_memory=8192MB)

Fusing layers... Model Summary: 331 layers, 7.07943e+07 parameters, 6.81919e+07 gradients
                 all       5e+03    3.63e+04    0.000805     0.00217     0.00114    0.000857
Speed: 19.2/2.0/21.1 ms inference/NMS/total per 896x896 image at batch-size 8

COCO mAP with pycocotools... saving detections_val2017__results.json...
ERROR: pycocotools unable to run: list index out of range

I downloaded coco dataset for validation and made two separate folders for images and labels. In labels folder i used "nameoftheimage".txt files with data in format {cls,w,h,x,y}.
What may cause this results?

**Comment by SashaAlderson** [comment]
Plus in the first initialization, it prints a lot of the same output. I don't know if it may help to find a solution to this problem.
 
![image](https://user-images.githubusercontent.com/84590713/122654792-f82dda00-d177-11eb-804a-e70438544b94.png)

**Comment by SashaAlderson** [comment]
i found a problem, labels for classes were wrong.

**Comment by GuoQuanhao** [comment]
Hi, how do you solve this problem
