### ISSUE TITLE
About the conf_thres setting in test.py

### ISSUE THREAD

**Issue by jasonchenPJ** [WongKinYiu/ScaledYOLOv4#277]
Hi @WongKinYiu 
在test.py中，conf-thres預設為0.001(此外由train.py呼叫時也是如此)，
但實際在detect.py使用時則設為0.4，
想請問原因為何? 

感謝

**Comment by WongKinYiu** [comment]
mAP的計算來自全部輸出結果的積分
實際使用通常會選擇達到eer或特定precision/recall的threshold.

**Comment by jasonchenPJ** [comment]
感謝你的回覆，
想請問關於 "precision/recall的threshold" 這部分，
意思是可透過不同threshold來量測F1 score，藉此找出最佳之設定嗎?
謝謝

**Comment by WongKinYiu** [comment]
看應用來選擇threshold, 例如門禁系統嚴格要求precision, 瑕疵檢測系統嚴格要求recall, 人群計數系統需要好的F1 score.
