### ISSUE TITLE
Requirements file?

### ISSUE THREAD

**Issue by ghost** [WongKinYiu/ScaledYOLOv4#282]
What are the requirements.txt  to run this?

**Comment by WongKinYiu** [comment]
almost all of packages are installed in the docker image, 
for those missing packages, see:
https://github.com/WongKinYiu/ScaledYOLOv4/tree/yolov4-csp#installation

**Comment by ghost** [comment]
Thanks. how can i change mAP to 0.75 for testing?

**Comment by ghost** [comment]
Don't you have any requirement.txt file ?

**Comment by WongKinYiu** [comment]
`ap[:, 0]` is ap50, `ap[:, 1]` is ap55, ...
https://github.com/WongKinYiu/ScaledYOLOv4/blob/yolov4-large/test.py#L195

equirement.txt file is not in this repo, but in other repo.
https://github.com/WongKinYiu/yolor/blob/main/requirements.txt

**Comment by hammadyounas2008** [comment]
How to add weights like YOLOv4-P7?

**Comment by hammadyounas2008** [comment]
![ge](https://user-images.githubusercontent.com/70446516/123585694-0d041080-d7fd-11eb-8381-af6074254a3f.JPG)
