### ISSUE TITLE
train_batch*.jpg are shifted/corrupted

### ISSUE THREAD

**Issue by yusiyoh** [WongKinYiu/ScaledYOLOv4#290]
Hello,
 I am trying to train yolov4-csp pytorch on custom dataset (DriveU Traffic Light Dataset). I observed that the batch of train images are sort of shifted and seems meaningless, as shown below.
![wo_shift](https://user-images.githubusercontent.com/6302128/124607754-cf475d80-de76-11eb-9fd4-8bcf4dd3682b.PNG)

My test batch instead seems okay : 
![test_batch](https://user-images.githubusercontent.com/6302128/124607903-f1d97680-de76-11eb-9107-c80c2bb82622.PNG)

Another issue is about my labels. I created txt files for labels with state x center y center w and h and the values are normalized with width of image = 2048 and height = 1024, however as shown in the pictures, the bounding boxes are shifted too. Should I scale x y w h myself, like scaling 416/2048 * w and so on?

Thank you very much

**Comment by WongKinYiu** [comment]
i can not reproduce the shifted issue.
by the way, your test samples also have shifted issue.
maybe you could try to write the code to draw box on your image to check if your label is correct.

![image](https://user-images.githubusercontent.com/12152972/124673690-ec6a4380-deeb-11eb-837c-7ba7112b3705.png)

**Comment by yusiyoh** [comment]
I solved the issue with labels. But the shift of the images on train batch still exists.
