### ISSUE TITLE
Training in float16 vs float32

### ISSUE THREAD

**Issue by vishnubanna** [WongKinYiu/ScaledYOLOv4#301]
Is there a reason that in this repository, you are able to test on float16 but not train? based on my reading of the code, in training only float32 is utilized, am I missing something? is there a drop in performance if you were to train on float16?

**Comment by WongKinYiu** [comment]
we use mixed precision training.
https://github.com/WongKinYiu/ScaledYOLOv4/blob/yolov4-large/train.py#L15
