### ISSUE TITLE
Regarding model configuration

### ISSUE THREAD

**Issue by khg2478** [WongKinYiu/ScaledYOLOv4#305]
Hello,

I have a question regarding the model configuration, yolov4-p7 (https://github.com/WongKinYiu/ScaledYOLOv4/blob/yolov4-large/models/yolov4-p7.yaml).

   [-1, 3, BottleneckCSP2, [128]], # 35
   [-1, 1, Conv, [256, 3, 1]],
   [-2, 1, Conv, [256, 3, 2]],
   [[-1, 30], 1, Concat, [1]],  # cat
   [-1, 3, BottleneckCSP2, [256]], # 39
   [-1, 1, Conv, [512, 3, 1]],
   [-2, 1, Conv, [512, 3, 2]],
   [[-1, 25], 1, Concat, [1]],  # cat
   [-1, 3, BottleneckCSP2, [512]], # 43
   [-1, 1, Conv, [1024, 3, 1]],
   [-2, 1, Conv, [512, 3, 2]],
   [[-1, 20], 1, Concat, [1]],  # cat
   [-1, 3, BottleneckCSP2, [512]], # 47
   [-1, 1, Conv, [1024, 3, 1]],
   [-2, 1, Conv, [512, 3, 2]],
   [[-1, 15], 1, Concat, [1]],  # cat
   [-1, 3, BottleneckCSP2, [512]], # 51
   [-1, 1, Conv, [1024, 3, 1]],

It seems that from layer #35 below, every each first Conv layer (36, 40, 44, 48) is not connected with the model right? As the second layers are connected with the -2 layers individually. So, I wonder why the model is configured in this way?? Has this feature improved the performance??

**Comment by WongKinYiu** [comment]
They are connected with the model https://github.com/WongKinYiu/ScaledYOLOv4/blob/yolov4-large/models/yolov4-p7.yaml#L76

**Comment by khg2478** [comment]
Indeed.. how come I missed it.. thanks. Case closed.
