### ISSUE TITLE
results.txt headings

### ISSUE THREAD

**Issue by hidan98** [WongKinYiu/ScaledYOLOv4#313]
Could someone please tell me the associated headings for the results.txt file?

 191/199     11.1G   0.02945   0.02314         0   0.05259        14       640    0.6128    0.7442    0.7274    0.4041   0.03875   0.02167    0
 192/199     11.1G   0.02933   0.02244         0   0.05177         6       640    0.5783    0.7841    0.7326    0.4201    0.0376   0.02101      0
 193/199     11.1G   0.02943   0.02287         0   0.05229         3       640    0.5885    0.8073    0.7414    0.4215   0.03705   0.02111     0
 194/199     11.1G   0.02873   0.02371         0   0.05244        11       640    0.6115    0.7738     0.732    0.4131   0.03777   0.02098     0
 195/199     11.1G   0.02946   0.02269         0   0.05215        11       640    0.6182    0.7774    0.7299    0.4048   0.03843   0.02116    0
196/199     11.1G   0.02937   0.02269         0   0.05206        10       640    0.5956    0.7779    0.7354    0.4119   0.03837   0.02134     0
 197/199     11.1G    0.0299   0.02356         0   0.05346        17       640    0.5727    0.7641    0.7258    0.4176   0.03831   0.02128     0
   

thanks for your help

**Comment by WongKinYiu** [comment]
'Epoch', 'gpu_mem', 'IoU', 'obj', 'cls', 'total', 'targets', 'img_size' 'precision_val', 'recall_val', 'mAP_0.5_val', 'mAP_0.5:0.95_val', 'IoU_val', 'obj_val', 'cls_val'

**Comment by engrjav** [comment]
@WongKinYiu  I am very new to image processing and while training my dataset i am really confused about one thing.

If my number of annotations and number of images are same, why my targets are more than no of images?


What does this term target mean?


I know very basic to ask from you but i would really appreciate for the great help
