### ISSUE TITLE
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

### ISSUE THREAD

**Issue by shoxa-mir** [WongKinYiu/ScaledYOLOv4#318]
Hello,
I am trying to train model and got this issue.
If anyone faced similar problem please, help to fix it.

Thank you!

**Comment by jorgegaticav** [comment]
Im having the same problem, using both PyTorch 1.6.0 and 1.7.0

**Comment by DrChungAlbert** [comment]
I have the same problem ,using Pytorch 1.8.0 in conda env build ver.

**Comment by adakoda** [comment]
I also have same problem, but #240 solutions works fine.

- Solution A: Use the docker container as mentioned in the README
  - OK: nvcr.io/nvidia/pytorch:[20.06-py3](https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/rel_20-06.html#rel_20-06) (Pytorch 1.6.0) # docker container image version should be 20.06-py3
  - NG: nvcr.io/nvidia/pytorch:[21.07-py3](https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/rel_21-07.html#rel_21-07) (Pytorch 1.10.0)
 
or

- Solution B: Update code like [5fb6832](https://github.com/tbeatty/ScaledYOLOv4/commit/5fb6832f95fe808f6ed71243e77e1e07d93a4b67)
https://github.com/WongKinYiu/ScaledYOLOv4/blob/yolov4-large/utils/general.py#L1092
```
def output_to_target(output, width, height):
    for i, o in enumerate(output):
        if o is not None:
            for pred in o.cpu():
                box = pred[:4]
```

**Comment by jorgegaticav** [comment]
> I also have same problem, but #240 solutions works fine.
> 
> * Solution A: Use the docker container as mentioned in the README
>   
>   * OK: nvcr.io/nvidia/pytorch:[20.06-py3](https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/rel_20-06.html#rel_20-06) (Pytorch 1.6.0) # docker container image version should be 20.06-py3
>   * NG: nvcr.io/nvidia/pytorch:[21.07-py3](https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/rel_21-07.html#rel_21-07) (Pytorch 1.10.0)
> 
> or
> 
> * Solution B: Update code like [5fb6832](https://github.com/tbeatty/ScaledYOLOv4/commit/5fb6832f95fe808f6ed71243e77e1e07d93a4b67)
>   https://github.com/WongKinYiu/ScaledYOLOv4/blob/yolov4-large/utils/general.py#L1092
> 
> ```
> def output_to_target(output, width, height):
>     for i, o in enumerate(output):
>         if o is not None:
>             for pred in o.cpu():
>                 box = pred[:4]
> ```

It worked, thanks!
