### ISSUE TITLE
Using yolov4-csp.cfg with pytorch implementation

### ISSUE THREAD

**Issue by yusiyoh** [WongKinYiu/ScaledYOLOv4#333]
I am using this command:
python3 train.py --img 640 --batch 12 --epochs 60 --data 'data/dtld_20.yaml' --cfg ./models/yolov4-csp.cfg --weights './yolo/weights/yolov4-csp.weights' --name yolov4-csp-bulb_dir-CFG --cache

And get the following error:
![image](https://user-images.githubusercontent.com/6302128/133444312-faf19fb8-7b48-464d-845a-5b64aa0d5a5c.png)

My cfg file is here(converted to txt to send from github):
[yolov4-csp.txt](https://github.com/WongKinYiu/ScaledYOLOv4/files/7170565/yolov4-csp.txt)

**Comment by WongKinYiu** [comment]
it seems you are using yolov4-large branch, this branch do not support .cfg format.
if you want to use .cfg for training, please use yolov4-csp branch.
