### ISSUE TITLE
How can I save only the model parameters?

### ISSUE THREAD

**Issue by Fateeeeee** [WongKinYiu/ScaledYOLOv4#350]
Now the weight size saved by YOLOv4-CSP has reached 400MB. What do I need to do to save only the model parameters in the weight file?

**Comment by WongKinYiu** [comment]
the saved weights contains both of weights and optimizer for supporting resume training. if you save only weights in the training process, it will unable to resume training when your training is interrupted. after finish training, you could delete optimizer and convert weights to fp16 to reduce size of weights file as you want by loading ckpt and modify the content.

**Comment by Fateeeeee** [comment]
Thanks for your reply, i know how to do it.
