### ISSUE TITLE
Setting up repo without using docker 

### ISSUE THREAD

**Issue by Edwardius** [WongKinYiu/ScaledYOLOv4#352]
Can anyone provide any instructions for setting up ScaledYOLOv4 without using the docker image? That or any pointers on how to make a dockerfile out of nvcr.io/nvidia/pytorch:20.11-py3

Thanks

**Comment by jackhu-bme** [comment]
https://github.com/WongKinYiu/ScaledYOLOv4/issues/144

**Comment by jackhu-bme** [comment]
You can look at this link and it's carefully dicussed. This helped me successfully run this code.
