### ISSUE TITLE
Adjust hyperparameters to compare equally

### ISSUE THREAD

**Issue by jackhu-bme** [WongKinYiu/ScaledYOLOv4#353]
I made some changes  to the original code and wanna test if they could work.
I need to confirm the hyperparameters and other basic settings are consistent with yours.
If I want to get the same mAP of YOLO-p5 model by training on COCO datast in your paper, is it right to simply download the COCO dataset and your current code and  run this command:
`python -m torch.distributed.launch --nproc_per_node 4 train.py --batch-size 64 --img 896 896 --data coco.yaml --cfg yolov4-p5.yaml  --sync-bn --device 0,1,2,3 --name yolov4-p5-tune --hyp 'data/hyp.scratch.yaml' --epochs 450 `
and test like what's written in your readme.md.
What modifications should I make?Any to hyp or epochs or other things? I need to compare equally and don't want to spend too much time modify these things. Thanks a lot for your help!

**Comment by WongKinYiu** [comment]
if you want to get same results: https://github.com/WongKinYiu/ScaledYOLOv4#training
if you want to get better results: https://github.com/WongKinYiu/yolor/issues/82

**Comment by jackhu-bme** [comment]
Thanks so much for your help!
