### ISSUE TITLE
load model error

### ISSUE THREAD

**Issue by ifzhang** [WongKinYiu/ScaledYOLOv4#47]
Thanks for your wonderful work! 
I run test.py and load yolov4-p5.pt and the error is :
Traceback (most recent call last):
  File "/home/yfzhang/PycharmProjects/YOLO/test.py", line 269, in <module>
    test(opt.data,
  File "/home/yfzhang/PycharmProjects/YOLO/test.py", line 55, in test
    model = attempt_load(weights, map_location=device)  # load FP32 model
  File "/home/yfzhang/PycharmProjects/YOLO/models/experimental.py", line 137, in attempt_load
    model.append(torch.load(w, map_location=map_location)['model'].float().fuse().eval())  # load FP32 model
  File "/home/yfzhang/anaconda3/envs/YOLO/lib/python3.8/site-packages/torch/serialization.py", line 595, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/yfzhang/anaconda3/envs/YOLO/lib/python3.8/site-packages/torch/serialization.py", line 774, in _legacy_load
    result = unpickler.load()
ModuleNotFoundError: No module named 'mc'

**Comment by WongKinYiu** [comment]
https://github.com/WongKinYiu/ScaledYOLOv4/tree/yolov4-large#installation

**Comment by ifzhang** [comment]
Do you have the installation for conda environment? Thank you very much!

**Comment by WongKinYiu** [comment]
For install mish_cuda as mc, the steps are same for docker and conda.

**Comment by WongKinYiu** [comment]
```
cd /yolo
git clone https://github.com/thomasbrandon/mish-cuda mc
cd mc

# change all of name which is mish_cuda to mish_mish and build.
# 1. mc/src/mish_cuda -> mc/src/mish_mish
# 2. mc/csrc/mish_cuda.cpp -> mc/csrc/mish_mish.cpp
# 3. in mc/setup.py
#   3.1 line 5 -> 'csrc/mish_mish.cpp'
#   3.2 line 11 -> name='mish_mish'
#   3.3 line 20 -> 'mish_mish._C'

python setup.py build
# rename mc/build/lib.xxx folder to mc/build/lib

# modify import in models/common.py
# line 7 -> from mc.build.lib.mish_mish import MishCuda as Mish
```

**Comment by ifzhang** [comment]
Thank you very much!

**Comment by WongKinYiu** [comment]
also thanks for your fairmot project.
