### ISSUE TITLE
about detect result

### ISSUE THREAD

**Issue by enazoe** [WongKinYiu/ScaledYOLOv4#58]
您好 @WongKinYiu ，感谢您的工作，
我有一点疑问，我用项目中提供的模型 [yolov4-csp.cfg](https://github.com/WongKinYiu/ScaledYOLOv4/blob/yolov4-csp/models/yolov4-csp.cfg)和权重 [yolov4-csp.weights](https://drive.google.com/file/d/1NQwz47cW0NUgy7L3_xOKaNEfLoQuq3EL/view?usp=sharing)，在darknet框架下执行 `darknet.exe detector test cfg/coco.data cfg/yolov4-csp.cfg cfg/yolov4-csp.weights -i 0 -thresh 0.25` 得到的detect结果是这样的

![predictions](https://user-images.githubusercontent.com/19791587/100563440-563cc200-32f9-11eb-8e76-dc9e1eadcbbe.jpg)

已经在cfg中修改`[yolo] new_coords=1`，不知道还有其他地方需要修改吗？

**Comment by WongKinYiu** [comment]
https://github.com/WongKinYiu/ScaledYOLOv4/issues/42#issuecomment-732803075

result on pytorch:
![image](https://user-images.githubusercontent.com/12152972/100573600-25698680-3313-11eb-8828-113d6ff2f257.png)

result on darknet:
![image](https://user-images.githubusercontent.com/12152972/100573514-ef2c0700-3312-11eb-969a-40aad2c14b53.png)

**Comment by enazoe** [comment]
好的，感谢，我的darknet不是最新版本，更新到最新版本结果正确
