### ISSUE TITLE
[8, 1, Conv, [256, 1, 1]], # route backbone P4 .yaml中的这个写法好像有bug~

### ISSUE THREAD

**Issue by Pluto1314** [WongKinYiu/ScaledYOLOv4#59]
您好，最近我在使用YOLOv5的时候，我发现好像不能直接填之前的层。
比如这个8，应该是backbone的P4层，但是在yolo.py的parse_model()方法里面，ch是从通道为3开始的，也就是说这个8用到的实际上是backbone的红线那一层了。
![image](https://user-images.githubusercontent.com/47765770/100621916-38a04480-335b-11eb-9e3e-1eca3873e4f8.png)

我觉得是不是应该修改成下面这样：
![image](https://user-images.githubusercontent.com/47765770/100622076-64bbc580-335b-11eb-93e8-100b0a238db9.png)

我不知道是不是我理解错了。。。

**Comment by WongKinYiu** [comment]
要直接填的話要用 -1, -2, ...才保證不會有問題
填正數的話channel會抓錯層 不過route到的層還是對的

修正此bug有兩個地方要改, 只要`f`為負數就是`ch[f]`只要`f`為正數就是`ch[f+1]`.
例如:
[conv](https://github.com/WongKinYiu/ScaledYOLOv4/blob/yolov4-large/models/yolo.py#L188)...: `c1, c2 = ch[f if f < 0 else f + 1], args[0]`
[concat](https://github.com/WongKinYiu/ScaledYOLOv4/blob/yolov4-large/models/yolo.py#L218): `c2 = sum([ch[x if x < 0 else x + 1] for x in f])`

**Comment by Pluto1314** [comment]
我明白了，非常感谢您详细的回复！
另外，我想请问一下这里的route P4指的是什么意思呢
![image](https://user-images.githubusercontent.com/47765770/100685586-9ebab500-33b7-11eb-861e-49d6978593a8.png)

**Comment by WongKinYiu** [comment]
![image](https://user-images.githubusercontent.com/12152972/100686600-9f544b00-33b9-11eb-8f54-79864166b671.png)

**Comment by Pluto1314** [comment]
好的好的，我下去看看。感谢您的回复~

**Comment by Pluto1314** [comment]
我将会关闭这个issue，再次感谢您~
