### ISSUE TITLE
train p7

### ISSUE THREAD

**Issue by daben233-bit** [WongKinYiu/ScaledYOLOv4#62]
Hi, thanks for your great work! I am trying to train p7 on 2080ti * 4 with batch size 4 and resolution 1536, but it tells me out of memory. Are you train your model on rtx titan?

**Comment by daben233-bit** [comment]
tesla v100, I found in the paper,   orz

**Comment by JustinhoCHN** [comment]
> tesla v100, I found in the paper, orz

Still can not train p7 on tesla V100@16GB, maybe only works on V100@32GB......

**Comment by WongKinYiu** [comment]
you could try https://github.com/WongKinYiu/yolor
new model save a lot of ram in training process.
![image](https://user-images.githubusercontent.com/12152972/118217633-711a8180-b4a8-11eb-8aa1-d07eb71605f1.png)
