### ISSUE TITLE
What is the code 'yolo'?

### ISSUE THREAD

**Issue by hi-one-gg** [WongKinYiu/ScaledYOLOv4#66]
![image](https://user-images.githubusercontent.com/13531174/101131453-a9d84400-3648-11eb-9391-973c0c85dfce.png)

I don't know what is the code 'yolo'.

Does it mean a darknet-yolov4 github code?

**Comment by WongKinYiu** [comment]
yolov4-csp github code

**Comment by hi-one-gg** [comment]
> yolov4-csp github code

Oh,,! Thank you owner !
