### ISSUE TITLE
Does anyone test yoloc4-csp FPS on Nvidia Jetson platform?

### ISSUE THREAD

**Issue by Underquant** [WongKinYiu/ScaledYOLOv4#67]

**Comment by saikrishnadas** [comment]
Nope, but I have a jetson nx and looking forward to testing it. But all the code around does inference for a batch of images and not single image inference. Is there any way to do single image inference? Each time an image is passed as input, it reloads the weight file making the time of inference high

**Comment by AlexeyAB** [comment]
It was tested by using Darknet: https://github.com/AlexeyAB/darknet
Use these cfg and weights files: https://github.com/AlexeyAB/darknet#pre-trained-models

**Comment by Underquant** [comment]
> It was tested by using Darknet: https://github.com/AlexeyAB/darknet
> Use these cfg and weights files: https://github.com/AlexeyAB/darknet#pre-trained-models

Thanks, I'll check it out.
