### ISSUE TITLE
运行完test.py，得到如下的结果和两张图片。意思是运行成功了吗

### ISSUE THREAD

**Issue by Wzh1997** [WongKinYiu/ScaledYOLOv4#72]
![image](https://user-images.githubusercontent.com/40290961/101324123-b1942480-38a4-11eb-9b2d-1eb3fc41127c.png)
![image](https://user-images.githubusercontent.com/40290961/101324155-bce75000-38a4-11eb-923f-af1756d36bd3.png)

运行完test.py，得到上面的结果和两张图片。意思是运行成功了吗。

![image](https://user-images.githubusercontent.com/40290961/101323889-506c5100-38a4-11eb-8476-ca0911046224.png)
为什么没有获得上面这些结果。

**Comment by WongKinYiu** [comment]
`pip install pycocotools`

**Comment by Wzh1997** [comment]
谢谢

**Comment by SpongeBab** [comment]
@Wzh1997 能帮我看看我的这个吗？
我的数据集是没问题的，但是为什么在训练时候生成的图片非常不正常。测试结果也很离谱。
https://github.com/WongKinYiu/ScaledYOLOv4/issues/205
