### ISSUE TITLE
original.pt or original_strip.pt

### ISSUE THREAD

**Issue by Pluto1314** [WongKinYiu/ScaledYOLOv4#73]
您好，请问一下original.pt 和 original_strip.pt有什么区别呀？
![image](https://user-images.githubusercontent.com/47765770/101348435-976b3e00-38c6-11eb-9621-0e5750c7f4ad.png)

**Comment by WongKinYiu** [comment]
strip會把optimizer宰掉, 還有一些資訊清掉, 可以當作pretrained weights.

**Comment by Pluto1314** [comment]
哦哦好的，谢谢您的回复~
