### ISSUE TITLE
How to see mAPs using test.py?

### ISSUE THREAD

**Issue by hi-one-gg** [WongKinYiu/ScaledYOLOv4#75]
When I try 

> `python test.py --img 896 --conf 0.001 --batch 8 --device 0 --data swoon.yaml --weights weights/yolov4-p5.pt`

I've received the result below. It's done.
![image](https://user-images.githubusercontent.com/13531174/101438474-cb417480-3955-11eb-998f-8bf83d7d5173.png)

My yaml is here : 
![image](https://user-images.githubusercontent.com/13531174/101438680-43a83580-3956-11eb-8b98-39b2c0c770ba.png)

And my data is here : 
![image](https://user-images.githubusercontent.com/13531174/101438724-5c185000-3956-11eb-8738-e601bcf06d2a.png)

How can I get result like below.
![image](https://user-images.githubusercontent.com/13531174/101438611-19ef0e80-3956-11eb-8df5-f532f7045946.png)

**Comment by WongKinYiu** [comment]
`pip install pycocotools`
and check if the annotation file is put in correct directory https://github.com/WongKinYiu/ScaledYOLOv4/blob/yolov4-large/test.py#L228

**Comment by hi-one-gg** [comment]
> `pip install pycocotools`
> and check if the annotation file is put in correct directory https://github.com/WongKinYiu/ScaledYOLOv4/blob/yolov4-large/test.py#L228

Oh I see Thank you : )
