### ISSUE TITLE
RuntimeError : Broken pipe.. How to solve?

### ISSUE THREAD

**Issue by hi-one-gg** [WongKinYiu/ScaledYOLOv4#77]
When I try to train my custom dataset I've met the error. 
How to solve it and why the error occurred?

![image](https://user-images.githubusercontent.com/13531174/101442557-eebced00-395e-11eb-9ed4-a7deb24d9ed9.png)

My gpu num is 3 not 4.
And my code in terminal is : 
`python -m torch.distributed.launch --nproc_per_node 4 train.py --batch-size 60 --img 896 896 --data swoon.yaml --cfg my_yolov4-p5.yaml --weights '' --sync-bn --device 0,1,2 --name my_yolov4-p5
`

**Comment by sirhikesalot** [comment]
I have the same issue @blackCmd. If you've found a fix please post!

**Comment by WongKinYiu** [comment]
if you have only three gpus, you could only train with maxima number of nproc_per_node equals to three, please try using `--nproc_per_node 3`.

by the way, if you get  oom error, try to reduce the batch size.
