### ISSUE TITLE
How to change period of mAP test ?

### ISSUE THREAD

**Issue by hi-one-gg** [WongKinYiu/ScaledYOLOv4#78]
When I training I can see mAP Test in every epoch.
How can I change the period of mAP test? 
=> i.g) I want to test mAP in every 10 epochs.

![image](https://user-images.githubusercontent.com/13531174/101445270-8bce5480-3964-11eb-9c40-de3fe2bf923e.png)

**Comment by WongKinYiu** [comment]
you could add `if (epoch % 10) == 0:` before [this line](https://github.com/WongKinYiu/ScaledYOLOv4/blob/yolov4-large/train.py#L306)

**Comment by hi-one-gg** [comment]
> you could add `if (epoch % 10) == 0:` before [this line](https://github.com/WongKinYiu/ScaledYOLOv4/blob/yolov4-large/train.py#L306)

Ohhhh, you are angle! 👼
