### ISSUE TITLE
How to test "mAP" on specific iou?

### ISSUE THREAD

**Issue by hi-one-gg** [WongKinYiu/ScaledYOLOv4#80]
![image](https://user-images.githubusercontent.com/13531174/101474642-ca790480-398e-11eb-8c72-998e52282f76.png)
I want to test not `mAP@0.5` or `mAP@0.5:0.95` but only `mAP@iou=0.8`.
Plz help me..  How can I do that? Where do I edit code?

### ADD QUESTION
I want to train using **IoU 0.8**. Is it possible? 
If it possible, How can I do that?

**Comment by WongKinYiu** [comment]
https://github.com/WongKinYiu/ScaledYOLOv4/blob/yolov4-large/test.py#L195
as i remember, ap[:, 0], ap[:, 1], ap[:, 2], ... are ap50, ap55, ap60...
you could try to change the index to get ap80, and use it in fitness function to save best.pt with best map80.

**Comment by hi-one-gg** [comment]
Ok. I'll try it  !
Thank you
