### ISSUE TITLE
When I train how to disable mosaic augmentation?

### ISSUE THREAD

**Issue by hi-one-gg** [WongKinYiu/ScaledYOLOv4#81]
When I train how to disable mosaic augmentation?

I've checked `run/yolov4-p6/train_batch*.jpg`
And I've noticed I trained using mosaic augmentation.

When I train how to disable mosaic augmentation?
I tried to edit hyp.*.yaml like below. But It didn't work.
![image](https://user-images.githubusercontent.com/13531174/101477708-f0080d00-3992-11eb-890c-ee8c2d47ebde.png)

**Comment by WongKinYiu** [comment]
`--rect`

**Comment by hi-one-gg** [comment]
> `--rect`

Unbelievable ! 😀
