### ISSUE TITLE
Output of Backbone

### ISSUE THREAD

**Issue by the-klingspor** [WongKinYiu/ScaledYOLOv4#85]
Hi,
thanks for the great paper and nice implementation. I want to implement a sampling strategy for active learning and for this I need features of my pictures that can be clustered. I'm wondering if there is a convenient way to access the backbone/CSPDarknet output of a YOLO model?
If it does not exist yet, I probably need to write a function similar to "forward_once" in "class Darknet" and return the output after calling the last layer of the backbone, correct?

Thanks for your help

**Comment by WongKinYiu** [comment]
yes, just send indexes of the layers you want to output to Detect layer, and modify the forward function of detect layer.

**Comment by the-klingspor** [comment]
Thanks for your help!
