### ISSUE TITLE
Map is so lower than yolov5...

### ISSUE THREAD

**Issue by hi-one-gg** [WongKinYiu/ScaledYOLOv4#86]
I trained my custom data using yolov4-p6. But the map was so low.
**(My custom dataset's nc is only 1)**
![image](https://user-images.githubusercontent.com/13531174/101666381-7e62b880-3a91-11eb-8c37-471fd19e5feb.png)

Then I trained the same data using yolov5l. But the map was so high.
![image](https://user-images.githubusercontent.com/13531174/101666572-ba961900-3a91-11eb-97b5-987299f9763e.png)

Is Yolov5 better than scaled-yolov4? -> I don't think so...
What is the problem? The hyp.yaml? The .cache file of my data?
Please help me. I tried to train using scaled-yolov4-p6 about ten times for three days..

**Comment by WongKinYiu** [comment]
what is your img-size for training?
yolov4-large compound scaling up input resolution, anchor, and stage.

if you are not sure for how to deal with it, you could train yolov4-csp with same img-size,  hyp.yaml and anchors as your previous training.

**Comment by AderonHuang** [comment]
hello,can you tell details or some files how to tensorboard to show these map pictures,if that, thanks very much

**Comment by hi-one-gg** [comment]
> what is your img-size for training?
> yolov4-large compound scaling up input resolution, anchor, and stage.
> 
> if you are not sure for how to deal with it, you could train yolov4-csp with same img-size, hyp.yaml and anchors as your previous training.

Img-size for training and test is 1280.
I've tried to train using yolov4-p5 and I get the 85mAP now. It is better than yolov4-p6... I don't know why is it happened

**Comment by yutao007** [comment]
i also  find it  when i train my custom data for yolov4 and yolov5s(the newest)  .the map@0.5 of  yolov5s(0.976) can be the same of yolov4 (0.967) ,but precision of yolov5(0.78) is too lower for yolov4 (0.96)

**Comment by hi-one-gg** [comment]
The reason is how many freeze layers.

**Comment by yutao007** [comment]
Under such conditions.  what criteria should we use to judge whether the model （yolov4  and  yolov5s）is good or bad.such as map@0.5  or  precision   
thanks  again

**Comment by engrjav** [comment]
@yutao007  when you train on yolov4p7 do you make any changes in backbone or head for custom dataset? (as alexAB advised to change number of filters for darknet yolov4) 
or just change number of classes?
